image: golang:1.7
stages:
  - build
  - test

before_script:
  - cp hello.go /go/src/
  - cd /go/src

build-my-project:
  stage: build
  script:
    - godep restore
    - godep go build

test-my-project:
  stage: test
  script:
    - godep restore
    - godep go test -v -cover ./...
